export const dynamic='force-dynamic';
export const runtime='nodejs';
import Papa from 'papaparse';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { prisma } from '../../lib/prisma';
const toOptional=(v?:string)=>{const t=(v??'').trim();return t||null};
async function importWholesale(formData:FormData){'use server';const file=formData.get('csvFile');if(!(file instanceof File)||file.size===0)redirect('/wholesale?status=invalid');const rows=Papa.parse(await file.text(),{header:true,skipEmptyLines:true,transformHeader:(h:string)=>h.toLowerCase().replace(/[^a-z0-9]/g,'')}).data;let count=0;for(const row of rows){const licenseeId=toOptional(row.licenseeid);if(!licenseeId)continue;await prisma.wholesaleAccount.upsert({where:{licenseeId},create:{licenseeId,agencyId:toOptional(row.agencyid),ownership:toOptional(row.ownership),name:toOptional(row.dba)??`Licensee ${licenseeId}`,address:toOptional(row.address),city:toOptional(row.city),county:toOptional(row.county),zip:toOptional(row.zipcode),districtId:toOptional(row.districtid),deliveryDay:toOptional(row.deliveryday),phone:toOptional(row.phonenumber)},update:{agencyId:toOptional(row.agencyid),ownership:toOptional(row.ownership),name:toOptional(row.dba)??`Licensee ${licenseeId}`,address:toOptional(row.address),city:toOptional(row.city),county:toOptional(row.county),zip:toOptional(row.zipcode),districtId:toOptional(row.districtid),deliveryDay:toOptional(row.deliveryday),phone:toOptional(row.phonenumber)}});count+=1;}revalidatePath('/wholesale');redirect(`/wholesale?status=imported&count=${count}`)}
export default async function WholesalePage({searchParams}:{searchParams?:Promise<{q?:string;status?:string;count?:string}>}){const params=(await searchParams)??{};const q=(params.q??'').trim();const accounts=await prisma.wholesaleAccount.findMany({take:200,where:q?{OR:[{name:{contains:q,mode:'insensitive'}},{address:{contains:q,mode:'insensitive'}},{phone:{contains:q,mode:'insensitive'}},{agencyId:{contains:q,mode:'insensitive'}},{licenseeId:{contains:q,mode:'insensitive'}}]}:undefined,orderBy:{name:'asc'}});return<><h1>Wholesale Accounts</h1><form method='get' style={{maxWidth:520}}><input name='q' defaultValue={q} placeholder='Filter by name, licensee ID, agency ID, address, phone'/></form>{params.status==='imported'?<p className='pill'>Imported/updated {params.count} wholesale accounts.</p>:null}<div className='card'><h2>Import Wholesale CSV</h2><form action={importWholesale}><input type='file' name='csvFile' accept='.csv,text/csv' required/><button type='submit'>Upload wholesale file</button></form></div><table><thead><tr><th>Licensee ID</th><th>Name</th><th>Agency ID</th><th>Address</th><th>City</th><th>Phone</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td>{a.licenseeId}</td><td>{a.name}</td><td>{a.agencyId}</td><td>{a.address}</td><td>{a.city}</td><td>{a.phone}</td></tr>)}</tbody></table></>}
