export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';
import Papa from 'papaparse';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { prisma } from '../../lib/prisma';
const toOptional = (v?: string) => { const t = (v ?? '').trim(); return t || null; };
const parseBool = (v?: string) => ['1','true','yes','y'].includes((v ?? '').trim().toLowerCase());
async function importAgencies(formData: FormData){'use server';const file=formData.get('csvFile');if(!(file instanceof File)||file.size===0)redirect('/agencies?status=invalid');const rows=Papa.parse(await file.text(),{header:true,skipEmptyLines:true,transformHeader:(h:string)=>h.toLowerCase().replace(/[^a-z0-9]/g,'')}).data;let count=0;for(const row of rows){const agencyId=toOptional(row.agencyid);if(!agencyId)continue;await prisma.agency.upsert({where:{agencyId},create:{agencyId,name:toOptional(row.dba)??`Agency ${agencyId}`,address:toOptional(row.address),city:toOptional(row.city),county:toOptional(row.county),zip:toOptional(row.zip),phone:toOptional(row.agencyphone),d8Permit:parseBool(row.d8permit),warehouse:toOptional(row.warehouse),orderDay:toOptional(row.orderday),orderWeek:toOptional(row.week),deliveryDay:toOptional(row.deliveryday),primaryContact:toOptional(row.primarycontact),primaryContactPhone:toOptional(row.primarycontactphone),wholesaleStatus:toOptional(row.wholesale)},update:{name:toOptional(row.dba)??`Agency ${agencyId}`,address:toOptional(row.address),city:toOptional(row.city),county:toOptional(row.county),zip:toOptional(row.zip),phone:toOptional(row.agencyphone),d8Permit:parseBool(row.d8permit),warehouse:toOptional(row.warehouse),orderDay:toOptional(row.orderday),orderWeek:toOptional(row.week),deliveryDay:toOptional(row.deliveryday),primaryContact:toOptional(row.primarycontact),primaryContactPhone:toOptional(row.primarycontactphone),wholesaleStatus:toOptional(row.wholesale)}});await prisma.locationContact.upsert({where:{id:`agency-${agencyId}-default`},create:{id:`agency-${agencyId}-default`,agencyId,name:toOptional(row.primarycontact)??`Agency Contact ${agencyId}`,phone:toOptional(row.primarycontactphone),role:"Primary Contact"},update:{name:toOptional(row.primarycontact)??`Agency Contact ${agencyId}`,phone:toOptional(row.primarycontactphone),role:"Primary Contact"}});count+=1;}revalidatePath('/agencies');redirect(`/agencies?status=imported&count=${count}`)}
export default async function AgenciesPage({searchParams}:{searchParams?:Promise<{q?:string;status?:string;count?:string}>}){const params=(await searchParams)??{};const q=(params.q??'').trim();const agencies=await prisma.agency.findMany({take:200,where:q?{OR:[{name:{contains:q,mode:'insensitive'}},{address:{contains:q,mode:'insensitive'}},{primaryContact:{contains:q,mode:'insensitive'}},{phone:{contains:q,mode:'insensitive'}},{agencyId:{contains:q,mode:'insensitive'}}]}:undefined,orderBy:{name:'asc'}});return<><h1>Liquor Agencies</h1><form method='get' style={{maxWidth:520}}><input name='q' defaultValue={q} placeholder='Filter by name, agency ID, address, contact, phone'/></form>{params.status==='imported'?<p className='pill'>Imported/updated {params.count} agencies.</p>:null}<div className='card'><h2>Import Agencies CSV</h2><form action={importAgencies}><input type='file' name='csvFile' accept='.csv,text/csv' required/><button type='submit'>Upload agencies</button></form></div><table><thead><tr><th>Agency ID</th><th>Name</th><th>Address</th><th>City</th><th>Primary Contact</th><th>Phone</th></tr></thead><tbody>{agencies.map(a=><tr key={a.id}><td>{a.agencyId}</td><td>{a.name}</td><td>{a.address}</td><td>{a.city}</td><td>{a.primaryContact}</td><td>{a.phone}</td></tr>)}</tbody></table></>}
